# Generated by Django 5.0.4 on 2024-04-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Order')], max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(choices=[('TL', 'Team_Lead'), ('MD', 'Mid_Lead'), ('JR', 'Junior')], max_length=10),
        ),
    ]
